change(lf): better git prompt detection.
Use `git rev-parse --is-inside-work-tree` to detect if the current directory is
a git repository. This is more reliable than checking for the presence of a
`.git` directory or file, as it also works for subdirectories of a git
repository.

diff --git a/.config/lf/lfrc b/.config/lf/lfrc
--- a/.config/lf/lfrc
+++ b/.config/lf/lfrc
@@ -14,8 +14,8 @@ set promptfmt "\033[1;31m[\033[1;33m%u\033[1;32m@\033[1;34m%h \033[1;35m%d\033[1
 
 cmd on-cd &{{
 	# display repository status in your prompt
-	if [ -d .git ] || [ -f .git ]; then
-		branch=$(git branch --show-current 2>/dev/null) || true
+	if git rev-parse --is-inside-work-tree >/dev/null 2>&1 && ! git check-ignore -q .; then
+		branch=$(git branch --show-current 2>/dev/null) || true  # fails on submodules
 		remote=$(git config --get branch.$branch.remote 2>/dev/null) || true
 		url=$(git remote get-url $remote 2>/dev/null) || true
 		repo="\033[33;1m [GIT URL:> $url]\033[0m"
